### ISSUE TITLE
Impls for BTreeSet and BTreeMap requiring PartialEq?

### ISSUE THREAD

**Issue by mohtar** [rust-lang-nursery/rustc-serialize#101]
The Encodable and Decodable implementations for the types BTreeSet and BTreeMap go like this:

    impl<T: Encodable + PartialEq + Ord> Encodable for BTreeSet<T>
    impl<T: Decodable + PartialEq + Ord> Decodable for BTreeSet<T>
    impl<K: Encodable + PartialEq + Ord, V: Encodable + PartialEq> Encodable for BTreeMap<T>
    impl<K: Decodable + PartialEq + Ord, V: Decodable + PartialEq> Decodable for BTreeMap<K, V>

What's the reasoning behind requiring PartialEq in these impls? I found out that PartialEq is rather unnecessary and the code compiles just fine without it:

    impl<T: Encodable + Ord> Encodable for BTreeSet<T>
    impl<T: Decodable + Ord> Decodable for BTreeSet<T>
    impl<K: Encodable + Ord, V: Encodable> Encodable for BTreeMap<T>
    impl<K: Decodable + Ord, V: Decodable> Decodable for BTreeMap<K, V>

**Comment by shepmaster** [comment]
This was fixed in #129, I think.
