### ISSUE TITLE
Implement support for serializing `Box<[u8]>` and other pointers of `[u8]`

### ISSUE THREAD

**Issue by reem** [rust-lang-nursery/rustc-serialize#103]
This should work basically the same as with `Vec<u8>`.

**Comment by Parakleta** [comment]
Related to this, also add the reference generic:

```rust
impl<'a, T: ?Sized + ToJson> ToJson for &'a T {
    fn to_json(&self) -> Json { (**self).to_json() }
}
```

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
