### ISSUE TITLE
Implement Decodable for FromStr and Encodable for ToString

### ISSUE THREAD

**Issue by james-darkfox** [rust-lang-nursery/rustc-serialize#105]
Hello all,

When trying to encode/decode `SocketAddr` I noticed that it was neither encodable or decodable despite implementing both 'ToString' and 'FromStr'.

``` rust
fn main() {
    if let Ok(ref addr) = "127.0.0.1:1234".parse::<std::net::SocketAddr>() {
        println!("{:?} == {:?}", addr.to_string(), addr)
    }
}
```

```
"127.0.0.1:1234" == V4(127.0.0.1:1234)
```

Here the `to_string()` almost gives us an `Encodable` type and `parse/FromStr` almost gives us a `Decodable` type.

Any chance that we can get the following?

``` rust
impl<T: std::string::ToString> Encodable for T { }
impl<T: std::str::FromStr> Decodable for T { }
```

Cheers,
DarkFox.

**Comment by eugene-bulkin** [comment]
The problem with this is that without impl specialization, `impl<T: ToString> Encodable for T` will conflict with several other trait implementations. So until impl specialization is in, we can't do much about that.

**Comment by Boscop** [comment]
Would it be possible to include an impl of Encodable/Decodable for SocketAddr in rustc-serialize?

**Comment by james-darkfox** [comment]
@Boscop It is equally as held back by the lack of specialization.

**Comment by Boscop** [comment]
@james-darkfox Do you know what I can use as a encodable/decodable **monotonic** timestamp since 1970? I haven't found any such time type, all the types from std::time like Instant, SystemTime etc. can't even be converted to/from string.

**Comment by james-darkfox** [comment]
@Boscop That is irrelevant to this thread. Your question may be better asked on `reddit/r/rust` or on IRC. `ircs://irc.mozilla.org:6697/#rust` and `ircs://irc.mozilla.org:6697/#rust-offtopic`

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
