### ISSUE TITLE
Support struct field renaming

### ISSUE THREAD

**Issue by aloucks** [rust-lang-nursery/rustc-serialize#106]
There needs to be a way to rename struct fields for use with `#[derive(RustcDecodable, RustcEncodable)]`.

For example:

``` rust
#[derive(RustcDecodable, RustcEncodable)]
struct Thing {
    #[serialize(decode_name="type", encode_name="type")]
    type_ : String
}
```

**Comment by fuchsnj** [comment]
https://github.com/serde-rs/serde already has something like this
```
struct Thing {
    #[serde(rename="type")]
    type_ : String
}
```
or if you want different names for different serializations...
```
struct Thing {
    #[serde(rename(json="type", xml="type2"))]
    type_ : String
}
```

**Comment by redlolgeerf** [comment]
but serde is not a proper replacement for rustc-serialize, as it's missing some drammatic features like deserealising only part of json fields https://github.com/serde-rs/serde/issues/60

**Comment by fuchsnj** [comment]
@redlolgeerf I agree serde is not a proper replacement. I was showing that as an example of how it could be implemented.

**Comment by redlolgeerf** [comment]
@fenhl , my point is that requested feature is a needed one, despite presence of libraries, that do have it.

**Comment by fenhl** [comment]
cc @fuchsnj (assuming @redlolgeerf's comment was supposed to be directed at them)

**Comment by aidanhs** [comment]
I'm interested in this.

**Comment by erickt** [comment]
@redlolgeerf: The soon to be released serde v0.7.0 will by default automatically ignore unknown fields, with an attribute that restores the old behavior.

**Comment by sjmackenzie** [comment]
any movement on this?

**Comment by norru** [comment]
Has this been implemented yet?

**Comment by dtolnay** [comment]
Now that Serde is a proper replacement for rustc-serialize (and more), I think the idea is you should use Serde if you need to customize the serialized representation in any way, including renaming fields.

```rust
#[derive(Serialize, Deserialize)]
struct Thing {
    #[serde(rename = "type")]
    ty: String
}
```

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
