### ISSUE TITLE
json::Encoder should use std::io::Write instead of std::fmt::Write

### ISSUE THREAD

**Issue by jnicholls** [rust-lang-nursery/rustc-serialize#111]
I am guessing fmt::Write is being used for legacy reasons (core vs. std, and that rustc-serialize used to be in std?) but I think it makes more sense to have json::Encoder use an I/O writer instead, so serialization can write in a streaming fashion rather than to an in-memory String.

For now, I have an IoFmtWriter utility struct that holds a ref to an io::Write type, and implements fmt::Write on top of it.  This is my workaround for now, but I think it should be solved permanently in this crate.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
