### ISSUE TITLE
Require a `Stream` that could parse `Json` from a `std::io::Read`

### ISSUE THREAD

**Issue by zonyitoo** [rust-lang-nursery/rustc-serialize#124]
1. `Stream` initiates with a `&mut std::io::Read`.
2. `Stream::next` will return one `Json` if succeed.
3. Differ from `json::Builder`: 
   - `json::Builder` will check the tailing characters, and `Stream` won't
   - `json::Builder` accepts an `Iterator<Item=char>` while `Stream` accepts a `std::io::Read`.

May need to refactor the `json::Parser` for working with `std::io::Chars`.

**Comment by dtolnay** [comment]
In Serde you would use a [`StreamDeserializer`](https://docs.serde.rs/serde_json/struct.StreamDeserializer.html) which you can construct from an iterator of bytes or an io::Read and it gives you an iterator of deserialized values of type T of your choice.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
