### ISSUE TITLE
Enum variants with discriminants

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang-nursery/rustc-serialize#127]
Consider the following enum:

``` rust
enum Foo {
    Bar = -42,
}
```

Looking at the `Encoder` trait, it doesn’t seem that there’s an interface provided to extract the `isize` value assigned to an enum variant when encoding it. I wonder if it’s really the case, and what’s the reasoning behind this decision. Thank you.

Regards,
Ivan

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
