### ISSUE TITLE
Float fields are not required, and get NaN value when missing

### ISSUE THREAD

**Issue by nixpulvis** [rust-lang-nursery/rustc-serialize#128]
This seems like a pretty scary bug, my float fields in a structs being decoded to are being set to `NaN` when they are missing instead of giving the expected `MissingFieldError`.

Here is a minimal example of this issue.

``` rust
extern crate rustc_serialize;

use rustc_serialize::json;

#[derive(RustcDecodable, RustcEncodable)]
struct FloatTest {
    foo: u32,
}

fn main() {
    let float_struct: FloatTest = json::decode("{\"bar\": 3.14}").unwrap();
    println!("{}", float_struct.foo);
}
```

**Comment by SingingTree** [comment]
If I'm reading the code correctly it looks like when the parser attempts to read a field and cannot find the name, it adds null to the stack of values being parsed and parses that instead. From `read_struct_field` starting at line 2225 of json.rs:

```rust
// Add a Null and try to parse it as an Option<_>
// to get None as a default value.
self.stack.push(Json::Null);
 match f(self) {
    Ok(x) => x,
    Err(_) => return Err(MissingFieldError(name.to_string())),
}
```

The Decoder returns a NaN when parsing a null for floats (line 2120 of json.rs):

```rust
Json::Null => Ok(f64::NAN),
```
There are tests semi indicating this is desired behaviour: `test_decode_struct_with_nan`, but this is somewhat down to NaN being encoded as null normally.

I've tried tinkering around with this a bit, but messing with one piece breaks others and without more discussion around this I don't want to get too deep into any one particular path.

**Comment by dtolnay** [comment]
In Serde the behavior is controlled by attributes:

```rust
#[macro_use]
extern crate serde_derive;
extern crate serde_json;

#[derive(Deserialize, Debug)]
struct FloatTest {
    // set to None if missing
    a: Option<f32>,

    // set to `<f32 as Default>::default()` if missing, which is 0
    #[serde(default)]
    b: f32,

    // set to the result of calling `nan()` if missing
    #[serde(default = "nan")]
    c: f32,

    // required, otherwise deserialization returns an error
    d: f32,
}

fn nan() -> f32 {
    ::std::f32::NAN
}

fn main() {
    println!("{:?}", serde_json::from_str::<FloatTest>(r#" {"d":1} "#).unwrap());
}
```

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
