### ISSUE TITLE
Implement Ord for Json

### ISSUE THREAD

**Issue by defuz** [rust-lang-nursery/rustc-serialize#133]
For now `Json` doesn't implement trait `std::cmp::Ord`. As far as I understand it, the reason is using of `f64` inside it that disallow total ordering because of rule `NaN != NaN`. But JSON standard doesn't allow the use of `NaN`. This means that any valid JSON is total ordered, but technically it is not so.

So my suggestion is to manually implement trait `Ord` for `Json` (Deriving is not working because of `f64`). This will allow as to create structures like `BTreeMap<Json, _>`. If maintainers will agree with this, I can try to implement it.

**Comment by defuz** [comment]
Btw I think that all these arguments are suitable for `Eq`.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
