### ISSUE TITLE
Base64: Expose `STANDARD_CHARS` and `URLSAFE_CHARS`

### ISSUE THREAD

**Issue by KellerFuchs** [rust-lang-nursery/rustc-serialize#137]
Hello,

Exposing the actual character arrays -- directly or, preferably, through a `CharacterSet` method -- would make it much easier to implement `ToBase64` outside of the `base64` module.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
