### ISSUE TITLE
How to decode a partially unknown JSON format?

### ISSUE THREAD

**Issue by itarato** [rust-lang-nursery/rustc-serialize#138]
I have a string to JSON decode, where the format is partially known, eg:

```
{
  "prop1": 123, // u32
  "prop2": "foobar", // String
  "data": ... // Unknown format, can be numeric, string, object or array.
}
```

My current understanding is I can use a (1) structured decoder based on (for example) a struct that implements Decodable (the main type and all included subtypes) or use (2) `Json::from_str(&str) -> Json`.

My question is - can I use (1) - decoding to a struct, but keep the unknown part type generic (rustc_serialize:::json::Json)? The following example is not compiling but shows the idea:

``` rust
#[derive(RustcDecodable)]
struct MyType {
  prop1: u32,
  prop2: String,
  data: rustc_serialize:::json::Json,
}
```

This won't compile as Json is not implementing Decodable trait. The issue with Json::from_str() is that it results the full tree in Json type and I cannot use my typed struct for the parts known at least. However having the Json type for only the custom parts would be perfect.

I was reading the code and wondered if the Decoder's read_struct or read_enum would be helpful if I implement the Decodable trait myself, however didn't have luck with those either.

Do you recommend a different approach maybe? Or I'm just missing an obvious link?

**Comment by softprops** [comment]
I'm running into the same issue. I'm dealing with a json response from a server where one of the fields is defined as any valid json. I'm trying to wrangle this with a custom decoder impl without much luck :/

**Comment by yanns** [comment]
same issue here

**Comment by dtolnay** [comment]
This is a limitation of the design of rustc-serialize. One of the big reasons that Serde exists is to support this use case. The Serde equivalent is serde_json::Value which can be deserialized from any valid JSON.

```rust
#[derive(Deserialize)]
struct MyType {
    prop1: u32,
    prop2: String,
    data: serde_json::Value,
}
```

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
