### ISSUE TITLE
Make Json type decodable

### ISSUE THREAD

**Issue by lorenz** [rust-lang-nursery/rustc-serialize#141]
I have a data structure which contains some JSON in the form of a `Json` object. I can't derive `RustcDecodable` for the whole structure because `Json` doesn't implement Decodable. Is there any particular reason the `Decodable` trait is not implemented?

**Comment by softprops** [comment]
I'm having the the same issue

**Comment by Razican** [comment]
Same issue here too :(

**Comment by vorot93** [comment]
Json structure could be used as a variant for dynamic configuration. I support this feature.

**Comment by dtolnay** [comment]
This is a limitation of the design of rustc-serialize and is one of the big reasons that Serde exists with a design that supports this. The Serde equivalent is serde_json::Value which can be deserialized from any valid JSON. If you need this feature, you should probably be using Serde instead.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
