### ISSUE TITLE
Make it clear what the status of this crate is.

### ISSUE THREAD

**Issue by nixpulvis** [rust-lang-nursery/rustc-serialize#144]
I've been reading and hearing from many people now that `serde` is the future. However both this crate and serde don't just a huge amount of traffic. It's not obvious to someone looking to serialize something (like JSON) what crate to use, and what the end game is for Rust's serialization story. This being in the nursery makes me feel like it's the _right_ choice, but that goes against what I've heard.

Choosing a serialization library is often one of the first things many projects require, I recommend making this process easier for users.

**Comment by nathanaeljones** [comment]
I'm asking a similar question - particularly around json parsing. If one expects their JSON schema to evolve, and wishes to provide the most informative validation errors to the client, what library is most appropriate for parsing? Should one eschew codegen solutions? Serde on stable requires a lot of boilerplate and compile time.

**Comment by chpio** [comment]
@nathanaeljones serdes source gen should be obsolete on arrival of macros 1.1.

**Comment by algesten** [comment]
[@steveklabnik said on reddit](https://www.reddit.com/r/rust/comments/5i71d8/procedural_macros_rfc_merged/db64ahj/?) that macros 1.1 "just missed 1.14" and that they "will be stable in 1.15".

Combine that with [@alexcrichton commenting on this lib](https://github.com/rust-lang-nursery/rustc-serialize/issues/100#issuecomment-96103076), that "we hope to deprecate it one day".

My take this lib's days are numbered. Maybe marked as deprecated already some time in 2017 after 1.15 lands? My bet is either go with serde or deal with deprecation warnings in a few months.

**Comment by dtolnay** [comment]
Update from @brson in https://github.com/rust-lang/blog.rust-lang.org/pull/145#issuecomment-276862043:

> I don't think we are ready to claim that rustc-serialize is deprecated yet (I haven't heard anybody say it). But we could explicitly say "instead of rustc-serialize, try serde and let the authors know what you think", or even more forceful. It seems prudent to me to see how the serde stable experience goes, and think through the consequences further, before deprecating.

**Comment by frewsxcv** [comment]
Serde just had its 1.0 release! Has there been any discussion about long term plans (like years out) to phase out rustc-serialize? Is it too early to put a message on the README indicating they should probably be using serde?

**Comment by alexcrichton** [comment]
I'm currently discussing w/ the libs team how we'd like to approach this in terms of timeline and how to do it. Hopefully more on this soon!

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
