### ISSUE TITLE
Buggy deriving of RustcEncode when multiple module with a method encode() are in scope

### ISSUE THREAD

**Issue by NougatRillettes** [rust-lang-nursery/rustc-serialize#151]
As shown in this [MCVE](https://play.rust-lang.org/?gist=4855336da123370b3fdd9ef689917453&version=stable&backtrace=0) (by SO user [ker](https://stackoverflow.com/users/1103681/ker)) deriving of `RustcEncode` leads to error E0034 if there is any Trait with an `encode()` method in Scope.

As shown [here](https://stackoverflow.com/questions/36565194/multiple-impl-candidate-while-deriving-an-instance-in-rust?noredirect=1#comment60736768_36565194) it can be troublesome when using both `rustc-serialize` and `radix_tree` crates.

**Comment by NougatRillettes** [comment]
Possibly related to: #61. But I have no idea how `derive` works.

**Comment by cholcombe973** [comment]
I unfortunately hit this bug also a few minutes ago

**Comment by NougatRillettes** [comment]
It is now allegedly fixed by commit to rust-lang by @oli-obk.
