### ISSUE TITLE
getting the hex outta here

### ISSUE THREAD

**Issue by softprops** [rust-lang-nursery/rustc-serialize#152]
This crate is my tried and true crate for serialization. I've recently been getting the sense that serde is filling parts of the problem space this crate addresses. I've converted a few projects to serde primarily for json serialization. What now feels awkward is having dependency on 2 crates that have json serialization support for the need of other utilities that serde does provide, namely hexing. Do you ( the maintainers ) think think there's value in lifting the hex bits embedded in this crate into its own crate? I'd be happy to own that if you wouldn't want to feel burdened with managing the maintenance of that.

**Comment by alexcrichton** [comment]
Yeah hex and base64 likely don't belong in this crate any more, although there are already `hex` and `base64` crates on crates.io and perhaps those suffice?

**Comment by softprops** [comment]
oh lovely. [this](https://github.com/KokaKiwi/rust-hex/blob/master/src/lib.rs) is just want I wanted. Thanks!
