### ISSUE TITLE
JSON decoding errors when reading string from stream

### ISSUE THREAD

**Issue by varunagrawal** [rust-lang-nursery/rustc-serialize#163]
I am converting a string to JSON and then transferring it over TCP to a server.
### Client:

```
let json_data = json::encode(&message.as_str()).unwrap();
println!("Json data: {}", json_data);
stream.write_all(&json_data.as_bytes()).unwrap();
```

The println! above gives the string: `"{\"x\": 0.0, \"y\": 0.0, \"z\": 0.0, \"a\": 0.0, \"b\": 0.0, \"c\": 0.0}"`
### Server:

```
let mut buffer = [0; 512];
let mut stream = stream.unwrap();

// read the data from the TCP stream
let sz = stream.read(&mut buffer).unwrap();
// Potential bug: when retrieving a string from 
let s = String::from_utf8_lossy(&buffer[..sz]);
let data = s.trim();            
let json_ = Json::from_str(&data).unwrap();
```

When I read a stream, I get a `str` object like this: `"{\"x\": 0.0, \"y\": 0.0, \"z\": 0.0, \"a\": 0.0, \"b\": 0.0, \"c\": 0.0}"`.

The `Json::from_str()` method throws two errors in this case:
- ParseError: Because of the starting and ending double quotes (before and after the curly braces) leading to a `trailing characters` syntax error.
- The second is that because of the escape character `\` it is reading the JSON as `"{\\\"x\\\": 0.0, \\\"y\\\": 0.0, \\\"z\\\": 0.0, \\\"a\\\": 0.0, \\\"b\\\": 0.0, \\\"c\\\": 0.0}"` i.e. it is double escaping and thus does not return it as a valid object.

Currently I am using a very hacky solution where I am trimming the first and last character of the string and replacing all instances of `\` with empty strings. 

Anything I am doing wrong or is this a bug?

**Comment by varunagrawal** [comment]
IMHO the JSON converter should first check if it is valid JSON and then encode accordingly, rather than blindly assuming string values.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
