### ISSUE TITLE
JSON Parsing Tests by seriot.ch

### ISSUE THREAD

**Issue by duesee** [rust-lang-nursery/rustc-serialize#166]
Just wanted to report here. See http://seriot.ch/json/parsing_pruned.html#34 and http://seriot.ch/parsing_json.html. Red means that the parser crashed.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
