### ISSUE TITLE
Crate publish

### ISSUE THREAD

**Issue by ustulation** [rust-lang-nursery/rustc-serialize#174]
Hey guys, do you have a rough idea when is this going to get a new crates.io publish ? We require the merged  https://github.com/rust-lang-nursery/rustc-serialize/pull/173 . If it's not going to be anytime soon, we'll just hand-code it for now in our code-base (as we need to push to crates ourselves). 

Thanks

**Comment by alexcrichton** [comment]
Done!

**Comment by ustulation** [comment]
You guys are awesome :smile: !
