### ISSUE TITLE
Implement ToHex (and friends) for AsRef

### ISSUE THREAD

**Issue by Philipp91** [rust-lang-nursery/rustc-serialize#176]
I have a function that returns something which is `AsRef<[u8]>` and I want to turn it into a hexadecimal String. Today, I have to write `that_method(...).as_ref().to_hex()`. Is it possible to implement `ToHex` for `AsRef`, so that the code shortens to `that_method(...).to_hex()`?

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
