### ISSUE TITLE
from_hex should accept odd length slices

### ISSUE THREAD

**Issue by crypto-universe** [rust-lang-nursery/rustc-serialize#184]
[ramp's to_str_radix](https://aatch.github.io/ramp/ramp/int/struct.Int.html#method.to_str_radix) methon can return string with odd length (like "2AC"), which can't be serialized by from_hex method directly.
Workaround will lead to one more heap allocation :(
On the other hand, padding is not so trivial.
1) For math purposes example string should be padded to "02AC";
2) For [OCRA](https://tools.ietf.org/html/rfc6287) it must be padded like "2AC0".

Is it possible to add extra parameter to from_hex function (or second implementation), which will padd hex string with predefined strategy?

PS: If yes, I can write a PR :)

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
