### ISSUE TITLE
Add a comparison with serde to the documentation

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang-nursery/rustc-serialize#185]
It isn't clear when to choose rustc-serialize vs. serde. Having some documentation about this would be helpful.

**Comment by dtolnay** [comment]
The answer is always use Serde. :smiley_cat:

This is going to be resolved by deprecating rustc-serialize in Rust 1.18 - see [Rust release milestone predictions](https://internals.rust-lang.org/t/rust-release-milestone-predictions/4591?u=dtolnay).

**Comment by jrmuizel** [comment]
It might be worth making this coming deprecation more clear in the README.md and the documentation. 

Here's a list of crates first uploaded in April and March of 2017 that depend on rustc-serialize:

   [tuf](https://crates.io/crates/tuf)
   [xor](https://crates.io/crates/xor)
   [article-date-extractor](https://crates.io/crates/article-date-extractor)
   [azure-sdk-rust](https://crates.io/crates/azure-sdk-rust)
   [b2sum](https://crates.io/crates/b2sum)
   [biscuit](https://crates.io/crates/biscuit)
   [cargo-pack](https://crates.io/crates/cargo-pack)
   [cargo-pack-docker](https://crates.io/crates/cargo-pack-docker)
   [cargo-testjs](https://crates.io/crates/cargo-testjs)
   [git2_codecommit](https://crates.io/crates/git2_codecommit)
   [helix](https://crates.io/crates/helix)
   [hex2ascii](https://crates.io/crates/hex2ascii)
   [image-base64](https://crates.io/crates/image-base64)
   [kwatch](https://crates.io/crates/kwatch)
   [noise_search](https://crates.io/crates/noise_search)
   [nuform](https://crates.io/crates/nuform)
   [oauth-client-fix](https://crates.io/crates/oauth-client-fix)
   [opus_tools](https://crates.io/crates/opus_tools)
   [ozelot](https://crates.io/crates/ozelot)
   [poe-superfilter](https://crates.io/crates/poe-superfilter)
   [pokemon](https://crates.io/crates/pokemon)
   [record-query](https://crates.io/crates/record-query)
   [rls-analysis](https://crates.io/crates/rls-analysis)
   [rls-data](https://crates.io/crates/rls-data)
   [rls-span](https://crates.io/crates/rls-span)
   [rust-argon2](https://crates.io/crates/rust-argon2)
   [rust_keylock](https://crates.io/crates/rust_keylock)
   [rxor](https://crates.io/crates/rxor)
   [ryb_game](https://crates.io/crates/ryb_game)
   [secure-session](https://crates.io/crates/secure-session)
   [servo-websocket](https://crates.io/crates/servo-websocket)
   [snow](https://crates.io/crates/snow)
   [sovrin-client](https://crates.io/crates/sovrin-client)
   [stscli](https://crates.io/crates/stscli)
   [swindon](https://crates.io/crates/swindon)
   [tk-cantal](https://crates.io/crates/tk-cantal)
   [tokio-thrift](https://crates.io/crates/tokio-thrift)
   [tokio-thrift-bin](https://crates.io/crates/tokio-thrift-bin)
   [tokio-thrift-codegen](https://crates.io/crates/tokio-thrift-codegen)
   [traffic_generator](https://crates.io/crates/traffic_generator)
   [typographic_linter](https://crates.io/crates/typographic_linter)
   [pq](https://crates.io/crates/pq)

**Comment by alexcrichton** [comment]
I've been intending to propose to the libs team that we should develop a plan for the deprecation of rustc-serialize and messaging of migration to serde, but I haven't had time to do that unfortunately.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.

**Comment by dtolnay** [comment]
Actually this was sort of done. :laughing: 660c18a02f8a7aca84380353be8a34e5a49568c4
