### ISSUE TITLE
Support to read raw json  from Decoder object

### ISSUE THREAD

**Issue by rohitjoshi** [rust-lang-nursery/rustc-serialize#43]
I have a json string (used for Apple Push Notification Service : https://github.com/rohitjoshi/apns ) whose value can be either a string or other json object.   e.g  `{ "alert" : "Hello world!!" }`  or  `{ "alert" : {"body": "Hello, world!", "action-loc-key": "Open"} }`

To define this I am using  enum as

```
 enum AlertPayloadType  {
     AlertString(String),
     AlertDictionary(BTreeMap)
}
```

Now, to parse the json string ,  I have implemented  ToJson/Decoder traits in which I need to read raw string to determine  whether value is string or dictionary and convert into appropriate object but there is no function available in Decoder trait to retrieve Json object.

I tried to use read_str() function which works fine for String data type but due to `expect!(self.pop(), String)`  validation, it return error rather than converting Json object into string.

**Is it possible to modify read_str() as below**

```
fn read_str(&mut self) -> DecodeResult<string::String> {
    //expect!(self.pop(), String)
   match self.pop() {
        Json::Null => Ok("".to_string()),
        value => Ok(format!("{}", value)),
    }
}
```

For more details on what I am trying to do, see 
https://github.com/rohitjoshi/apns/blob/master/src/message.rs#L98   which invokes `ApnsMessage::to_alert_payload_type()` at https://github.com/rohitjoshi/apns/blob/master/src/message.rs#L127

**Comment by oli-obk** [comment]
I suggest using Json::from_str or from_reader since your issue is Json-specific and and afaik not what Encodable/Decodable are to be used for.

**Comment by rohitjoshi** [comment]
@oli-obk  Issue is with limitation in the Decoder trait interface which doesn't allow to access underneath object for custom manipulation. 

I tried using Json::from_str  which doesn't work  due to json string can have variable type of the value. e.g   alert key value could be string or dictionary as per Apple Push Notification specifications.

e.g `{ "alert" : "Hello world!!" }` or `{ "alert" : {"body": "Hello, world!", "action-loc-key": "Open"} }`

I think this can be resolve by 3 way.

1.  rustc_serialize::Decoder trait expose a method to return underline type. Not sure Rust would alllow this.   e.g `fn read<T>(&mut self)-> DecodeResult<T> {} `

2. Modify read_str() in json.rs as below which will return string representation of the object
    
   

        fn read_str(&mut self) -> DecodeResult<string::String> {
          //expect!(self.pop(), String)
        match self.pop() {
              Json::String(v) => Ok(v),
              value => Ok(value.to_string()),
          }
         }

3.  Add read_json() method for Decoder implementation for Json


`

    impl Decoder {
         fn pop(&mut self) -> Json {
             self.stack.pop().unwrap()
         }
        // new method
         pub fn read_json(&mut self) -> Json {
             self.stack.pop().unwrap()
         }
     }


`

**Comment by oli-obk** [comment]
even if you use the 3rd version. The Decodable has no access to the actual decoder, only to the trait. Without negative trait bounds this won't work (not sure if it works with them)
The 1st version requires specialization of generics (which would allow a full rewrite to a nicer interface to the serialization lib).
The 2nd version breaks the contract with the function and would only serve your special case.

**Comment by rohitjoshi** [comment]
@oli-obk  Thanks for the details.  I am new to Rust and trying to understand.  
Regarding 2nd version,  instead of modifying existing `read_str()`, we might want to add `read_as_string()` which sets expectation of getting converted string response.

**Comment by oli-obk** [comment]
read_as_string() would not make sense in a binary decoder though. As the Binary might be something not representable as a string.
Basically you should assume that Decoder can only decode types with a derived RustcEncodable trait that Encoder.

What you could do, is to decode your input to a BTreeMap<string, Json> and then match on the Json object.

**Comment by rohitjoshi** [comment]
@oli-obk  I guess it would be same issue for existing `read_str()` method in Decoder trait for binary decoder.

Don't you think suggested option 2 is better which will return string representation of object rather than returning error at runtime.

I wish Rust supported selective override of trait method. :)

**Comment by rohitjoshi** [comment]
@alexcrichton  do you think some support will be added to either pop json object or read_str() will stringify the object and return as string.

**Comment by softprops** [comment]
was there any resolution on this?

**Comment by rohitjoshi** [comment]
No but I had forked and implemented custom function.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
