### ISSUE TITLE
Add pop method to json Decoder

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/rustc-serialize#44]
<a href="https://github.com/yaitskov"><img src="https://avatars.githubusercontent.com/u/1292734?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yaitskov](https://github.com/yaitskov)**
_Thursday Sep 18, 2014 at 20:14 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/17377_

_This issue was labelled with:  in the Rust repository_

---

Now it's impossible to implement Decodable for a map with different value types
because read_\* methods lose the stack head anyway. 
Decodable doesn't have a method returning the stack head as-is without any type casting.

Let's look a case where Json dictionary has values with int and  String types.

```
extern crate serialize;
use serialize::{Decodable, Decoder};
use serialize::json::{Json, Boolean, String, Null, I64, U64, F64};
use serialize::json;

#[deriving(Show)]
struct Primitive(Json);

impl<S: Decoder<E>, E> Decodable<S, E> for Primitive {
    fn decode(decoder: &mut S) -> Result<Primitive, E> {
        match decoder.pop() {      
            n @ I64(_)    => Primitive(n),
            n @ U64(_)    => Primitive(n),
            n @ F64(_)    => Primitive(n),
            s @ String(_) => Primitive(s),
            bad           => fail!("bad {}", bad)
       }
    }
}
```

**Comment by oli-obk** [comment]
Note: Decodable is not a generic trait. The decode function is generic instead.
Note2: You can derive the Decodable implementation for BTreeMap<String, Option<String>> or any other enum type that derives Decodable as Value.

Obviously Note2 does not work to decode arbitrary json formats, only those that also were encoded by a derived Encodable trait.

As the decoder could also be any other decoder (like a binary decoder), the type of the field to read might not be available. Implementing a generic pop is therefor not possible. Making the pop method from json::Decoder public and waiting for negative trait bounds might work (https://github.com/rust-lang/rfcs/pull/586).

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
