### ISSUE TITLE
XML Support

### ISSUE THREAD

**Issue by mattnenterprise** [rust-lang-nursery/rustc-serialize#45]
Will this library ever support XML?

**Comment by gbersac** [comment]
:+1:  I'd love it to be available too. I'll add an issue to also have yaml support. Having one rust library for all type of serialization would be awesome !

What would be even more interesting would be to have an abstraction over the different type of data independant of the encoding language. Example :

```rust
let data1 = xml::from_string(xml_string); // return a Node structure
let data2 = yaml::from_string(yaml_string); // also return a Node structure
let data3 = json.from_string(json_string); // also return a Node structure
```

**Comment by dtolnay** [comment]
The response from the other ticket seems relevant here as well:

> This would be awesome! I suspect it would not be a part of this library, however, but rather done as an external crate.
>
> Right now we're not looking to expand this library too much as we hope to deprecated it one day (fingers crossed!). With crates.io and Rust traits, however, it's super easy to make a high-quality library externally, and it also keeps the compile times down for everyone using `rustc-serialize` who doesn't require YAML encoding/decoding. An example of a library like this is [toml](https://crates.io/crates/toml)

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
