### ISSUE TITLE
Better Option support in Hash/Objects

### ISSUE THREAD

**Issue by kali** [rust-lang-nursery/rustc-serialize#50]
It would be nice, in JSON ser/deser to map an optional key in a json objet to an Option<_> field in a struct. "None" would map from/to the absence of the key/value pair in the json object.

As far as I can tell, the current implementation makes it non-trivial as values are serialized separately from their key.

**Comment by dtolnay** [comment]
In Serde, deserialization supports this by default:

```rust
#[macro_use]
extern crate serde_derive;
extern crate serde_json;

#[derive(Deserialize, Debug)]
struct S {
    opt: Option<String>,
}

fn main() {
    println!("{:?}", serde_json::from_str::<S>("{}").unwrap());
}
```

And serialization treats None as null by default but you can use an attribute to selectively omit the entire map entry in the case of None:

```rust
#[macro_use]
extern crate serde_derive;
extern crate serde_json;

#[derive(Serialize)]
struct S {
    #[serde(skip_serializing_if = "Option::is_none")]
    opt: Option<String>,
}

fn main() {
    println!("{}", serde_json::to_string(&S { opt: None }).unwrap());
}
```

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
