### ISSUE TITLE
serialize::json is encouraging allocating intermediate buffers

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/rustc-serialize#57]
<a href="https://github.com/huonw"><img src="https://avatars.githubusercontent.com/u/1203825?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [huonw](https://github.com/huonw)**
_Tuesday Jul 01, 2014 at 23:58 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/15317_

_This issue was labelled with: A-libs in the Rust repository_

---

The `Encodable`/`Decodable` interface is designed to avoid having to allocate everything to intermediate buffers, but `json` is encouraging going via `String`. `serialize::json` has the top level `encode` function returning a `String`, and _all_ the examples use `encode` directly, there's no demonstration of the good direct-to-`Writer` API.

That is, something like

``` rust
println!("{}", json::encode(&x))
```

can be written a little like

``` rust
encodable.encode(&mut json::Encoder::new(&mut io::stdout()))
```

If that is deemed too ugly, I think we should work on fixing the ergonomics of the good version, rather than just leaping straight to the `-> String`  ones (e.g. `json::encode(&mut io::stdout(), &x)` would be nice, and work with `json::encode(&mut some_file, &x)`, `json::encode(&mut some_tcp_stream, &x)`, etc.).

cc @aturon

**Comment by oli-obk** [comment]
For decoding the entire source iterator is consumed, everything is converted to `Json` objects, and then decoded to the final type, dropping the `Json` objects.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
