### ISSUE TITLE
serialize::base64 could use a Show type

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/rustc-serialize#58]
<a href="https://github.com/seanmonstar"><img src="https://avatars.githubusercontent.com/u/51479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [seanmonstar](https://github.com/seanmonstar)**
_Saturday Nov 01, 2014 at 23:36 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/18520_

_This issue was labelled with: A-libs in the Rust repository_

---

I have a string that when written to a writer, needs to be converted to base64. Currently I have to allocate a new string that is encoded, before passing it to fmt. 

I'd imagine some like `struct Base64Fmt<'a> { s: &'a str, c: Config}`.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
