### ISSUE TITLE
Generalize numeric primitive types on Json

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang-nursery/rustc-serialize#63]
Instead of what we have now:

``` rust
#[derive(Clone, PartialEq, PartialOrd, Debug)]
pub enum Json {
    I64(i64),
    U64(u64),
    F64(f64),
    String(string::String),
    Boolean(bool),
    Array(self::Array),
    Object(self::Object),
    Null,
}
```

do something like:

``` rust
#[derive(Clone, PartialEq, PartialOrd, Debug)]
pub enum Json<I: SignedInt, U: UnsignedInt, F: Float> {
    Int(I),
    UInt(U),
    Float(F),
    String(string::String),
    Boolean(bool),
    Array(self::Array),
    Object(self::Object),
    Null,
}
```

Forgive me if this is a terrible idea. I was thinking about some of my large JSON datasets and it'd be nice to be able to control the precision for each numeric type.

**Comment by frewsxcv** [comment]
This would definitely become more ergonomic when default parameters are implemented for generics. e.g.

```rust
pub enum Json<I=i64: SignedInt, U=u64: UnsignedInt, F=f64: Float> {
    ...
}
```

(assuming this is how these would work)

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
