### ISSUE TITLE
Decoder::read_seq requires infinite lookahead

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rustc-serialize#68]
Implementing Decoder for a representation that does not know the length of sequences ahead of time requires infinite lookahead, since the length needs to be known before the first element is parsed.

For example: if Json were not parsed to the Json enum as an intermediate, when a sequence is expected, the `read_seq` function would need to parse ahead until it finds the corresponding `]`.

Also, all the collection implementations in `collection_impls.rs` do not require the length to be known beforehand. They only use it as an optimization to reduce the number of allocations.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
