### ISSUE TITLE
Missing `Default` trait on `json::Json`

### ISSUE THREAD

**Issue by Byron** [rust-lang-nursery/rustc-serialize#71]
I am trying to implement a google bigquery `tabledata.insertAll` request, which requires me to allow arbitrary json data within the json-encoded data structure. The [official docs](https://cloud.google.com/bigquery/docs/reference/v2/tabledata/insertAll) present it like this:

``` json
{
  "kind": "bigquery#tableDataInsertAllRequest",
  "rows": [
    {
      "insertId": string,
      "json": {
        (key): (value)
      }
    }
  ]
}
```

The enclosing structure is implementing the `Default` trait (it's a requirement), which fails to auto-implement as `json::Json` doesn't implement it for some reason. To my mind, it could be implemented like this:

``` Rust
impl Default for Json {
    fn default() -> Json {
        Json::Null
    }
}
```

Do you think this can be done, or is there a reason to omit this trait ? 

Thank you

**Comment by dtolnay** [comment]
I agree, we have the equivalent in Serde: https://github.com/serde-rs/json/issues/224.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
