### ISSUE TITLE
`Encoder` trait is missing a way to create Errors

### ISSUE THREAD

**Issue by jgallagher** [rust-lang-nursery/rustc-serialize#76]
The `Decoder` trait includes

``` rust
fn error(&mut self, err: &str) -> Self::Error;
```

but the `Encoder` trait doesn't have an equivalent method. AFAICT, inside an implementation of `Encodable` like this:

``` rust
impl Encodable for Foo {
    fn encode<S: Encoder>(&self, s: &mut S) -> Result<(), S::Error> {
        /* ... */
    }
}
```

it's impossible to create an `S::Error` (other than by one of the `s.emit_xyz` methods failing).

**Comment by cheme** [comment]
+1 , I got the same need, I think some structure may be conditionally encodable (for instance I want to fail when a PathBuf in struct refers to a non existing file, it may also be the case for struct with lazy content).

**Comment by jdc2172** [comment]
+1 just encountered this. Also had a need for conditional encoding. For some reason decodable has it, but not encodable?

**Comment by dtolnay** [comment]
We definitely needed this in Serde. We have the [`ser::Error`](https://docs.serde.rs/serde/ser/trait.Error.html) trait for this purpose.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
