### ISSUE TITLE
Should not return an error on control characters in string 

### ISSUE THREAD

**Issue by pzol** [rust-lang-nursery/rustc-serialize#98]
Or should at least give the option to ignore them.

https://github.com/rust-lang/rustc-serialize/commit/f514d05b72766941248eb0a87285b57f8e396376#diff-53fb26f5f2a7c73aed739f3cf6a2c81aR1672

With this, if there is garbage within a string, you cannot decode the json in question

**Comment by dtolnay** [comment]
I would be against supporting this. If your data is not JSON, you should not be using a JSON parser to read it.

**Comment by alexcrichton** [comment]
I'm going to close this now that this crate is deprecated in favor of [serde](https://serde.rs). We're discontinuing feature development in rustc-serialize but will still continue to merge bug fixes if they arise.
